# Le container doit etre lancer avec l'option "-v /var/run/docker.sock:/var/run/docker.sock"
# Pour que le dind fonctionne  
FROM jenkins/jenkins:jdk11

USER root

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" && \
    apt-get update && apt install -y docker-ce 
